repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3

  - repo: local
    hooks:
      - id: export-requirements
        name: Export requirements.txt
        entry: ./export_requirements.sh
        language: script
        files: ^(pyproject.toml|poetry.lock)$
        always_run: true
