main:
    params: [input]
    steps:
    - extractPwdParcelsData:
        call: http.post
        args:
            url: 'https://us-central1-musa-344004.cloudfunctions.net/extract_phl_pwd_parcels'
            auth:
                type: OIDC
    - preparePwdParcelsData:
        call: http.post
        args:
            url: 'https://us-central1-musa-344004.cloudfunctions.net/prepare_phl_pwd_parcels'
            auth:
                type: OIDC
    - loadPwdParcelsData:
        call: http.post
        args:
            url: 'https://us-central1-musa-344004.cloudfunctions.net/load_pwd_parcels'
            auth:
                type: OIDC
