import pretty_errors

from utils.extract_data.extract_opa_properties import extract_phl_opa_properties
from utils.prepare_data.prepare_opa_properties import prepare_phl_opa_properties

# extract_phl_opa_properties()
prepare_phl_opa_properties()